### ISSUE TITLE
app location sensitive

### ISSUE THREAD

**Issue by jimlynnjulian** [preritdas/rottentomatoes-python#13]
Hello,

   I just attempted to run a script in two different folders. One was successful and one failed. The results were the same in Windows MS-DOS CLI (DOS box) and Microsoft WSL Ubuntu bash; with and without dos2unix text conversions.
The conclusion is the app is, for some reason, sensitive to the calling location. I have two copies of the code on my computer at two different locations. One is for version 0.5.16 and one 0.5.11. Once I cd out of the 0.5.16 directory, the scripts work. The scripts work in the 0.5.11 folder.
Is there one or more files that would be referenced if available locally when the script is run? Not a big issue. I can delete the 0.5.16 folder, or make sure not to run any scripts there.

The erroroneous attempt resulted in the following message:
python rtp-script01.py
Traceback (most recent call last):
  File "C:\Temp\Movie databases\rottentomatoes-python-0.5.16\rtp-script01.py", line 13, in <module>
    test()
  File "C:\Temp\Movie databases\rottentomatoes-python-0.5.16\rtp-script01.py", line 7, in test
    movie = rt.Movie('top gun maverick')
  File "C:\Temp\Movie databases\rottentomatoes-python-0.5.16\rottentomatoes\movie.py", line 21, in __init__
    self.tomatometer = standalone.tomatometer(self.movie_title, content=content)
  File "C:\Temp\Movie databases\rottentomatoes-python-0.5.16\rottentomatoes\standalone.py", line 155, in tomatometer
    return _get_score_details(content)['scoreboard']['tomatometerScore']["value"]
  File "C:\Temp\Movie databases\rottentomatoes-python-0.5.16\rottentomatoes\standalone.py", line 82, in _get_score_details
    return json.loads(
  File "C:\Python310\lib\json\__init__.py", line 339, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not NoneType

**Comment by preritdas** [comment]
Thanks for your comment and for using the library @jimlynnjulian. Over time, Rotten Tomatoes will update their website, resulting in various standalone scraping functions to stop working. 

The error you're displaying occurred after the release of 0.5.11 for the above reason. Since then, there have been several more site changes resulting in new releases. Please use the latest version exclusively (currently 0.5.18 as of this message) and report any issues if they arise.

**Comment by jimlynnjulian** [comment]
Thank you for your response.Perhaps I did not make myself clear.The app worked as advertised unless I ran the app from within the 0.5.16 folder created when I unzipped the downloaded archive.   Yes, I had already upgraded to the latest version. But as I said, after opening a MS-DO
S CLI window in a different folder, the app ran.I could run the sapp from a CLI ain any folder but the 0.5.16 folder.Just a FYI.
Hope this helps.
Thanks again.Jim J.

    On Thursday, June 8, 2023 at 02:24:11 PM EDT, Prerit Das ***@***.***> wrote:  
 
 


Thanks for your comment and for using the library @jimlynnjulian. Over time, Rotten Tomatoes will update their website, resulting in various standalone scraping functions to stop working.

The error you're displaying occurred after the release of 0.5.11 for the above reason. Since then, there have been several more site changes resulting in new releases. Please use the latest version exclusively (currently 0.5.18 as of this message) and report any issues if they arise.

**Comment by preritdas** [comment]
Thanks for clarifying @jimlynnjulian. I'm tempted to believe this is due to the way your Python interpreter is sourcing the package, because the library does not directly interact with your file system in any way. Nothing is written, deleted, or modified at any point. 

If this becomes an issue affecting usability, please let me know so we can properly diagnose it. Otherwise, I'll be closing this issue. 

Thanks again for using the library and for communicating some feedback.
